export const yieldStakingAbi = [
    {
        type: "constructor",
        inputs: [
            { name: "admin", type: "address" },
            { name: "operator", type: "address" },
            { name: "_stakeToken", type: "address" },
            { name: "_rewardToken", type: "address" },
        ],
        stateMutability: "nonpayable",
    },
    {
        type: "event",
        name: "Staked",
        inputs: [
            { name: "user", type: "address", indexed: true },
            { name: "packageId", type: "uint8", indexed: true },
            { name: "stakeId", type: "uint32", indexed: false },
            { name: "amount", type: "uint256", indexed: false },
            { name: "rewardTotal", type: "uint256", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Claimed",
        inputs: [
            { name: "user", type: "address", indexed: true },
            { name: "packageId", type: "uint8", indexed: true },
            { name: "stakeId", type: "uint32", indexed: false },
            { name: "amount", type: "uint256", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Withdrawn",
        inputs: [
            { name: "user", type: "address", indexed: true },
            { name: "packageId", type: "uint8", indexed: true },
            { name: "stakeId", type: "uint32", indexed: false },
            { name: "principal", type: "uint256", indexed: false },
            { name: "reward", type: "uint256", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "EmergencyWithdrawn",
        inputs: [
            { name: "user", type: "address", indexed: true },
            { name: "packageId", type: "uint8", indexed: true },
            { name: "stakeId", type: "uint32", indexed: false },
            { name: "principal", type: "uint256", indexed: false },
            { name: "lostReward", type: "uint256", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "ExcessRewardWithdrawn",
        inputs: [
            { name: "admin", type: "address", indexed: true },
            { name: "amount", type: "uint256", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "PackageUpdated",
        inputs: [
            { name: "id", type: "uint8", indexed: true },
            { name: "lockPeriod", type: "uint64", indexed: false },
            { name: "apy", type: "uint32", indexed: false },
            { name: "enabled", type: "bool", indexed: false },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleAdminChanged",
        inputs: [
            { name: "role", type: "bytes32", indexed: true },
            { name: "previousAdminRole", type: "bytes32", indexed: true },
            { name: "newAdminRole", type: "bytes32", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleGranted",
        inputs: [
            { name: "role", type: "bytes32", indexed: true },
            { name: "account", type: "address", indexed: true },
            { name: "sender", type: "address", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "RoleRevoked",
        inputs: [
            { name: "role", type: "bytes32", indexed: true },
            { name: "account", type: "address", indexed: true },
            { name: "sender", type: "address", indexed: true },
        ],
        anonymous: false,
    },
    {
        type: "event",
        name: "Paused",
        inputs: [{ name: "account", type: "address", indexed: false }],
        anonymous: false,
    },
    {
        type: "event",
        name: "Unpaused",
        inputs: [{ name: "account", type: "address", indexed: false }],
        anonymous: false,
    },
    {
        type: "function",
        name: "stakeToken",
        inputs: [],
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "rewardToken",
        inputs: [],
        outputs: [{ name: "", type: "address" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "packages",
        inputs: [{ name: "", type: "uint8" }],
        outputs: [
            { name: "lockPeriod", type: "uint64" },
            { name: "apy", type: "uint32" },
            { name: "enabled", type: "bool" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "userStakeCount",
        inputs: [
            { name: "", type: "address" },
            { name: "", type: "uint8" },
        ],
        outputs: [{ name: "", type: "uint32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "userStakeHistory",
        inputs: [
            { name: "", type: "address" },
            { name: "", type: "uint8" },
            { name: "", type: "uint32" },
        ],
        outputs: [
            { name: "balance", type: "uint128" },
            { name: "rewardTotal", type: "uint128" },
            { name: "rewardClaimed", type: "uint128" },
            { name: "lockPeriod", type: "uint64" },
            { name: "unlockTimestamp", type: "uint64" },
            { name: "lastClaimTimestamp", type: "uint64" },
        ],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "userTotalStakes",
        inputs: [{ name: "", type: "address" }],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "packageTotalStaked",
        inputs: [{ name: "", type: "uint8" }],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "totalLocked",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "totalRewardDebt",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "minStakeAmount",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "maxStakePerUser",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "maxTotalStakedPerPackage",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "setPackage",
        inputs: [
            { name: "id", type: "uint8" },
            { name: "lockPeriod", type: "uint64" },
            { name: "apy", type: "uint32" },
            { name: "enabled", type: "bool" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "pause",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "unpause",
        inputs: [],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "withdrawExcessReward",
        inputs: [{ name: "amount", type: "uint256" }],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "stake",
        inputs: [
            { name: "amount", type: "uint256" },
            { name: "packageId", type: "uint8" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "claim",
        inputs: [
            { name: "packageId", type: "uint8" },
            { name: "stakeId", type: "uint32" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "withdraw",
        inputs: [
            { name: "packageId", type: "uint8" },
            { name: "stakeId", type: "uint32" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "emergencyWithdraw",
        inputs: [
            { name: "user", type: "address" },
            { name: "packageId", type: "uint8" },
            { name: "stakeId", type: "uint32" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "getClaimableRewardsForStake",
        inputs: [
            { name: "user", type: "address" },
            { name: "packageId", type: "uint8" },
            { name: "stakeId", type: "uint32" },
        ],
        outputs: [{ name: "", type: "uint256" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getStakeCount",
        inputs: [
            { name: "user", type: "address" },
            { name: "packageId", type: "uint8" },
        ],
        outputs: [{ name: "", type: "uint32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "paused",
        inputs: [],
        outputs: [{ name: "", type: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "DEFAULT_ADMIN_ROLE",
        inputs: [],
        outputs: [{ name: "", type: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "ADMIN_ROLE",
        inputs: [],
        outputs: [{ name: "", type: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "OPERATOR_ROLE",
        inputs: [],
        outputs: [{ name: "", type: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "hasRole",
        inputs: [
            { name: "role", type: "bytes32" },
            { name: "account", type: "address" },
        ],
        outputs: [{ name: "", type: "bool" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "getRoleAdmin",
        inputs: [{ name: "role", type: "bytes32" }],
        outputs: [{ name: "", type: "bytes32" }],
        stateMutability: "view",
    },
    {
        type: "function",
        name: "grantRole",
        inputs: [
            { name: "role", type: "bytes32" },
            { name: "account", type: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "revokeRole",
        inputs: [
            { name: "role", type: "bytes32" },
            { name: "account", type: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
    {
        type: "function",
        name: "renounceRole",
        inputs: [
            { name: "role", type: "bytes32" },
            { name: "account", type: "address" },
        ],
        outputs: [],
        stateMutability: "nonpayable",
    },
] as const;
