export const UNAUTHORIZED_RESOURCE = "UNAUTHORIZED_RESOURCE";
export const FORBIDDEN_RESOURCE = "FORBIDDEN_RESOURCE";
export const NOT_FOUND = "NOT_FOUND";
export const BAD_REQUEST = "BAD_REQUEST";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";
export const TOKEN_INVALID = "TOKEN_INVALID";
