module.exports = {
    apps: [
        {
            name: 'backend-dev',
            script: 'node_modules/.bin/nest',
            args: 'start --watch',
            cwd: __dirname,
            watch: false,
            autorestart: true,
            max_restarts: 20,
            restart_delay: 2000,
            min_uptime: '5s',
            env: {
                NODE_ENV: 'development',
            },
            error_file: 'logs/pm2-error.log',
            out_file: 'logs/pm2-out.log',
            merge_logs: true,
            time: true,
        },
        {
            name: 'backend-prod',
            script: 'dist/main.js',
            cwd: __dirname,
            instances: 1,
            autorestart: true,
            max_restarts: 10,
            restart_delay: 3000,
            min_uptime: '10s',
            exp_backoff_restart_delay: 100,
            env: {
                NODE_ENV: 'production',
                BLOCKCHAIN_LISTENER_ENABLED: 'true',
                BLOCKCHAIN_AUTO_PROCESS_EVENTS: 'true',
                METAMASK_NONCE_CLEANUP_ENABLED: 'false',
            },
            error_file: 'logs/pm2-error.log',
            out_file: 'logs/pm2-out.log',
            merge_logs: true,
            time: true,
        },
        {
            name: 'backend-worker-blockchain-prod',
            script: 'dist/workers/blockchain-events.worker.js',
            cwd: __dirname,
            instances: 1,
            autorestart: true,
            max_restarts: 20,
            restart_delay: 3000,
            min_uptime: '10s',
            exp_backoff_restart_delay: 100,
            env: {
                NODE_ENV: 'production',
                BLOCKCHAIN_WORKER_BATCH: '50',
                BLOCKCHAIN_WORKER_IDLE_MS: '1000',
                BLOCKCHAIN_MAX_ATTEMPTS: '10',
                BLOCKCHAIN_LISTENER_ENABLED: 'false',
                BLOCKCHAIN_AUTO_PROCESS_EVENTS: 'false',
                METAMASK_NONCE_CLEANUP_ENABLED: 'false',
            },
            error_file: 'logs/pm2-worker-error.log',
            out_file: 'logs/pm2-worker-out.log',
            merge_logs: true,
            time: true,
        },
        {
            name: 'backend-listener-blockchain-prod',
            script: 'dist/workers/blockchain-listener.worker.js',
            cwd: __dirname,
            instances: 1,
            autorestart: true,
            max_restarts: 20,
            restart_delay: 3000,
            min_uptime: '10s',
            exp_backoff_restart_delay: 100,
            env: {
                NODE_ENV: 'production',
                BLOCKCHAIN_LISTENER_ENABLED: 'true',
                BLOCKCHAIN_LISTENER_ADVISORY_LOCK: 'true',
                BLOCKCHAIN_AUTO_PROCESS_EVENTS: 'false',
                METAMASK_NONCE_CLEANUP_ENABLED: 'false',
            },
            error_file: 'logs/pm2-listener-error.log',
            out_file: 'logs/pm2-listener-out.log',
            merge_logs: true,
            time: true,
        },
    ],
};
